### ISSUE TITLE
Make scenarios 3-chained-actions and 4-web-accessible-actions less verbose on startup

### ISSUE THREAD

**Issue by rafabene** [projectodd/openwhisk-katacoda#19]
Scenarios 3-chained-actions and 4-web-accessible-actions  aren't using the scripts that allow a less verbose start.

**Comment by evanchooly** [comment]
with the new environment that should be coming online today, this will get much less chatty as that config work will be done beforehand.

**Comment by evanchooly** [comment]
the new environment is not quite ready but I reworked these scripts and it's all but silent now.
